
Barttracht_m_temp = {'Schnurbart':'3-1',
'Schnurbart (dick)':'7-4',
'Schnurbart (dünn)':'10-8',
'Oberlippenflaum':'2-1',
'Kinnbart (kurz)':'4-3',
'Kinnbart (lang)':'6-5',
'Kotletten (lang)':'8-7',
'Vollbart (sehr kurz)':'10-9',
'Vollbart (sehr kurz)':'1',
'Vollbart (sehr kurz am Kinn länger)':'2',
'Vollbart (gestutzt)':'5-3',
'Vollbart (gestutzt, an den Wangen länger)':'6',
'Vollbart (gestutzt am Kinn länger)':'7',
'Vollbart (mittellang)':'9-8',
'Vollbart (mittellang, am Kinn länger)':'10',
'Vollbart (an den Wangen besonders lang)':'1',
'Vollbart (lang)':'2',
'Thierse-Gedächtnis-Bart':'3',
'Karl-Marx-Gedächtnisbart':'4',
'Kaiserlicher Backenbart (Schnurbart + Wangen + Kotletten, kein Kinnbart)':'5',
'Walroßbart (sehr langer Schnurbart)':'7-6',
'Knebelbart (Kinnbart mit gezwirbeltem Schnurbart)':'9-8',
'Fischerkrause (Vollbart minus Schnurrbart)':'10',
'Fischerkrause (Vollbart minus Schnurrbart)':'2-1',
'Unterlippenbart':'3',
'Henriquatre (Oberlippenbart und Kinnbart, verbunden)':'7-4',
'Schurbart und Unterlippenbart':'9-8',
'Kleiner Schnäuzer (aka Charlie- Chaplin-Bärtchen)':'10',
'Fuseln im Gesicht':'1',
'Drei-Tage-Bart':'2',
'Fuseln im Gesicht':'3',
'Drei-Tage-Bart':'5-4',
'Gabelbart':'7-6',
'Bart mit Zopf':'8',
'Bart mit Zöpfen':'9',
'Eckiger Vollbart':'10',
'kein Bart':'46-1'
}

Barttracht_w_temp = {
'kein Bart':'115-1',
                     'leichter Damenbart':'3-1',
                     '5-4': 'mittlerer Damenbart',
                     'starker Damenbart':'6'
                     }