berufe_temp = {'Fahrendes Volk' :{
'Wanderarbeiter':'5',
'Kiepenkerl oder Hausierer':'3',
'Scherenschleifer oder Kesselflicker':'2',
'Flüchtling':'1',
'Gaukler':'4',
'Musikant oder Barde':'2',
'Flüchtiger Verbrecher':'2',
'Söldner oder Abenteurer ':'1'},
'Mittellos' :{ 
'Knecht':'14',
'Tagelöhner':'28',
'Fischer ohne Boot':'6',
'Lumpenhändler':'6',
'Flüchtling oder Versehrter':'12',
'Abdecker':'3',
'Rattenfänger':'3',
'Bettler':'24',
'Dieb':'6',
'Einbrecher':'3',
'Wilderer':'3',
'Schmuggler, Schläger, Betrüger':'6',
'Totengräber':'2',
'Einsiedler oder Eremit':'3',
'Schelm ':'1'},
'Unterschicht' :{
'Bauer':'6',
'Knecht':'18',
'Tagelöhner':'12',
'Bediensteter':'6',
'Straßenhändler':'6',
'Schauerleute':'4',
'Fuhrknecht':'6',
'Flößer/ Fährmann':'2',
'einfacher Handwerker':'18',
'Wache':'1',
'Rattenfänger':'1',
'Jäger':'3',
'Henker':'1',
'Fischer':'12',
'Holzfäller':'6',
'Köhler':'6',
'Viehhüter':'6',
'Wirt':'1',
'Bedienung':'3',
'Koch ':'2'},
'Mittelschicht' :{
'Bauer':'12',
'Knecht':'6',
'Bedienstete':'6',
'Krämer':'18',
'Müller':'6',
'Händler':'12',
'Zunfthandwerker':'30',
'Gardist':'2',
'Schreiber oder Lehrer':'3',
'Botenreiter':'1',
'Fischer':'6',
'Viehzüchter':'6',
'Priester':'6',
'Wirt':'3',
'Koch ':'3'},
'Oberschicht' 
:{
'Gutsbesitzer':'20',
'Viehzüchter':'10',
'Magistrat oder Rechtsgelehrter':'6',
'Händler':'42',
'Priester':'6',
'Zunftmeister':'6',
'Magier oder Alchimist':'6',
'Hotelier':'6',
'Schiffseigner':'6',
'Gelehrter':'6',
'Reicher Erbe ':'6'},
'Adel' :{
 'Nicht Erstgeborener Taugenichts':'12',
 'Nicht Erstgeborener Mittelschichtberuf':'12',
 'Nicht Erstgeborener Oberschichtberuf':'48',
'Großhändler':'6',
'Stadtrat oder Bürgermeister':'6',
'Akademieleiter oder bedeutender Lehrer':'6',
'Edler oder Baron':'24',
'Baron':'6'}}