besonderheiten_temp = {'Albino':'2-1',
'Stumm':'6-4',
'Blind':'9-7',
'Schwerhörig':'10',
'Schwerhörig':'5-1',
'Einbeinig':'10-6',
'Einarmig':'6-1',
'Einhändig':'10-7',
'Einhändig':'2-1',
'Missbildung':'6-3',
'Steifes Bein':'10-7',
'Steifes Bein':'2-1',
'Buckel':'6-3',
'Gelähmter Arm':'10-7',
'Große Narbe':'4-1',
'Gesucht I':'10-5',
'Gesucht III':'1',
'Gesucht II':'4-2',
'Unentdeckter Mörder':'5',
'Unentdeckter Dieb':'8-6',
'Unentdeckter Betrüger':'10-9',
'Unentdeckter Betrüger':'2-1',
'Unentdeckter Ehebrecher':'7-3',
'Unentdeckter Wilderer':'10-8',
'Unentdeckter Wilderer':'1',
'Unentdeckter  Anbeter  des Namenlosen':'3-2',
'Unentdeckter  Dämonenanbeter (noch nicht Paktierer)':'5-4',
'Unentdeckter Vergewaltiger':'7-6',
'Unentdeckter Druide':'9-8',
'Unentdeckte Hexe':'10',
'Unentdeckte Hexe':'1',
'Unentdeckter Freigeist/Revolutionär':'3-2',
'Berüchtigter Schläger':'9-4',
'Ungewöhnlicher  Glaube  (Firun im  Süden  Aventuriens, Verehrung von Elementarherren,  Tierkönigen, etc.)':'10',
'Ungewöhnlicher  Glaube  (Firun im  Süden  Aventuriens, Verehrung von Elementarherren,  Tierkönigen, etc.)':'1',
'Sehr gläubig':'7-2',
'Hat Kind adoptiert':'9-8',
'Religiöse(r) Fanatiker(in)':'10',
'Religiöse(r) Fanatiker(in)':'3-1',
'Stigma  (Stärke: W6)':'6-4',
'Farbenblind':'10-7',
'Begabung  für Kampftalent':'2-1',
'Begabung  für Körperliches Talent':'6-3',
'Begabung  für Naturtalent':'10-7',
'Begabung  für Naturtalent':'1',
'Begabung  für Gesellschaftliches Talent':'7-2',
'Begabung  für Wissenstalent':'10-8',
'Begabung  für Wissenstalent':'1',
'Begabung  für Handwerkstalent':'8-2',
'Erstaunlich gebildet':'10-9',
'Erstaunlich gebildet':'2-1',
'Herausragendes Gedächtnis':'4-3',
'Feenfreund':'5',
'Koboldfreund':'6',
'Macht  fast  immer das was andere tun':'17',
'Macht fast nie das was andere tun':'8',
'Zwergenfreund':'10-9',
'Zwergenfreund':'2-1',
'Elfenfreund':'6-3',
'Schlangenmensch':'8-7',
'Wohlklang':'10-8',
'Wohlklang':'1',
'Gefahreninstinkt':'5-2',
'Leicht  magische Haare':'7-6',
'Speisegebote':'10-8',
'Magiegespür':'2-1',
'Pechvogel':'6-3',
'Glückspilz':'9-7',
'Witwe/Witwer/Waise':'10',
   'Witwe/Witwer/Waise':'9-1',
   'Prophetische Gabe':'10',
'Prophetische Gabe':'1',
'Schwul/lesbisch':'7-2',
'Bisexuell':'9-8',
'Bisexuell':'1',
'Asexuell':'4-2',
'Mondsüchtig':'8-5',
'Depression':'10-9',
'Depression':'6-1',
'Schizophrenie':'9-7',
'Hört Stimmen':'10',
'Hört Stimmen':'1',
'Soziale Phobie':'5-2',
'Alkoholiker/in':'10-6',
'Alkoholiker/in':'2-1',
'Zwangsstörung':'6-3',
'Einzelgänger':'10-7',
'Einzelgänger':'1',
'Süchtig':'4-2',
'Ehemaliger Sträfling':'8-5',
'Rassist':'10-9',
'Rassist':'3-1',
'Extremer Rassist':'7-4',
'Veteran einer Schlacht':'10-8',
'Veteran einer Schlacht':'2-1',
'Kriegsveteran':'4-3',
'Magiedilettant':'9-5',
'Fremde Kultur':'10',
'Fremde Kultur':'5-1',
'Hautkrankheit':'9-6',
'Krank  (Flinker  Difar, Triefnase, etc.)':'10',
'Krank  (Flinker  Difar, Triefnase, etc.)':'5-1',
'Schwer Erkrankt (Lungenentzündung, Krebs, etc.)':'9-6',
'Affinität zu Geistern':'10',
'Affinität zu Geistern':'1',
'Affinität zu Dämonen':'3-2',
'Albträume':'9-4',
'Sehr hoch verschuldet':'10',
'Hoch verschuldet':'5-1',
'Sehr gute Beziehungen':'8-6',
'Goldgierig':'10-9',
'Goldgierig':'4-1',
'Sehr goldgierig':'8-5',
'Geizig':'10-9',
'Geizig':'3-1',
'Sehr geizig':'7-4',
'Jähzornig':'10-8',
'Jähzornig':'2-1',
'Sehr jähzornig':'7-3',
'Abergläubisch':'10-8',
'Abergläubisch':'6-1',
'Sehr abergläubisch':'10-7',
'Sehr abergläubisch':'2-1',
'Neugierig':'9-3',
'Sehr neugierig':'10',
'Sehr neugierig':'3-1',
'Stubenhocker':'5-4',
'Hatte kürzlich einen Trauerfall in der Familie':'10-6',
'Hat einen Erzfeind':'3-1',
'Begrenzter Wortschatz':'5-4',
'Schwer verliebt':'10-6',
'Schwer verliebt':'2-1',
'Besitzt einen Schatz (100D+)':'5-3',
'Besitzt  einen  großen  Schatz (300D+)':'7-6',
'Tierfreund':'10-8',
'Hat Läuse':'6-1',
'Großer Wortschatz':'8-7',
'Hat Flöhe':'10-9',
'Hat Flöhe':'4-1',
'Viele Tatöwierungen':'6-5',
'Stinkt leicht':'10-7',
'Stinkt leicht':'2-1',
'Stinkt':'9-3',
'Mundgeruch':'10',
'Mundgeruch':'4-1',
'Riecht angenehm':'7-5',
'Riecht sehr angenehm':'9-8',
'Schluckauf':'10',
'Stark geschminkt':'3-1',
'Führt Selbstgespräche':'6-4',
'Ehemaliger Abenteurer':'8-7',
'Besitzt  ein  außergewöhnliches Tier':'10-9',
'Magnet  für  Ungewöhnliches':'1',
'Leidet an Epilepsie':'2',
'Hat einen sehr guten Ruf':'6-3',
'Hat einen sehr schlechten Ruf':'9-7',
'Hat einen schlechten Ruf':'10',
'Hat einen schlechten Ruf':'4-1',
'Hat einen guten Ruf':'10-5',
'Ihm/Ihr ist immer zu kalt':'3-1',
'Ihm/Ihr ist immer zu warm':'6-4',
'Schwitzt sehr viel':'10-7',
'Sehr groß (1,90 Schritt +)':'6-1',
'Sehr klein (1,50 schritt -)':'10-7',
'Sehr klein (1,50 schritt -)':'1',
'Oft geistesabwesend':'5-2',
'Verfressen':'9-6',
'Kleptomane':'10',
'Kleptomane':'1',
'kaut gerne Fingernägel':'5-2',
'sehr feuchte Aussprache':'7-6',
'Lichtscheu':'8',
'Sehr behaart':'10-9',
'Sehr behaart':'4-1',
'sehr vergesslich':'8-5',
'Unstet':'10-9',
'Unstet':'1',
'Arkanophobie':'3-2',
'Angst vor Spinnen':'8-4',
'Angst vor Nagetieren':'10-9',
'Angst vor Nagetieren':'3-1',
'Angst vor Schlangen':'8-4',
'Meeresangst':'10-9',
'Angst vor Feuer':'1',
'Dunkelangst':'2',
'Verflucht von Hexe':'4-3',
'Unter einem Schwur':'8-5',
'Hat  in  der  Vergangenheit  viel Gutes erlebt':'10-9',
'Hat  in  der  Vergangenheit  viel Gutes erlebt':'2-1',
'Hat  in  der  Vergangenheit  viel Schlechtes erlebt':'6-3',
'Hat  in  der  Vergangenheit  viel Ungewöhnliches erlebt':'10-7',
'Hat mal einen Geist gesehen':'3-1',
'Hat mal einen Dämon gesehen':'5-4',
'Hat  mal  einen  Drachen gesehen':'8-6',
'Hat mal einen Vampir gesehen':'9',
'Hat  mal  eine  Alveranier gesehen':'10',
'Hat mal eine Fee gesehen':'3-1',
'Wurde  unter  ungewöhnlichen Umständen geboren':'5-4',
'Adoptiert':'7-6',
'Frisch verheiratet':'10-8',
'Kürzlich  Vater/Mutter/ Opa/Oma  geworden':'4-1',
'Hat  kürzlich  wichtiges Vorhaben beendet':'7-5',
'Kürzlich  mit  wichtigem Vorhaben gescheitert':'10-8',
'Hat  kürzlich  etwas  wichtiges verloren':'2-1',
'Kann sehr gut lügen':'5-3',
'Kann sehr gut argumentieren':'8-6',
'Kann sehr gut feilschen':'10-9',
'Kann sehr gut feilschen':'1',
'Kann sehr gut kochen':'4-2',
'Wildniserfahren':'8-5',
'Gebirgskundig':'10-9',
'Sumpfkundig':'2-1',
'Hat reichen Verwandten':'6-3',
'Hat eine große Familie':'10-7',
'Hat nur eine kleine Familie':'3-1',
'Hat keine Familie':'5-4',
'Hat keine Freunde':'7-6',
'Hat viele Freunde':'9-8',
'Hat ein treues Haustier':'10',
'Hat ein treues Haustier':'2-1',
'Besitzt ein besonderes Buch':'4-3',
'Besitzt  ein  besonderes Schmuckstück':'7-5',
'Überdurchschnittlich wohlhabend':'10-8',
'Verglichen am Stand arm':'2-1',
'Feiert sehr gerne':'5-3',
'Nervöse Ticks':'7-6',
'Gewandt (GE > 14)':'10-8',
'Gewandt (GE > 14)':'3-1',
'Sehr gewandt (GE > 16)':'8-4',
'Äußerst gewandt (GE > 18)':'9',
'Äußerst geschickt (FF > 18)':'10',
'Geschickt (FF > 14)':'6-1',
'Sehr geschickt (FF > 16)':'9-7',
'Robust (KO > 14)':'10',
'Robust (KO > 14)':'6-1',
'Sehr robust (KO > 16)':'9-7',
'Äußerst robust (KO > 18)':'10',
'Stark (KK > 14)':'7-1',
'Sehr stark (KK > 16)':'10-8',
'Äußerst stark (KK > 18)':'1',
'Hohe Magieresistenz':'3-2',
'Zäher Hund':'5-4',
'Eisern':'7-6',
'Feste Prinzipien':'10-8',
'Feste Prinzipien':'1',
'Besonders praiosgläubig':'3-2',
'Besonders rondragläubig':'5-4',
'Besonders traviagläubig':'9-6',
'Besonders efferdgläubig':'10',
'Besonders efferdgläubig':'2-1',
'Besonders borongläubig':'4-3',
'Besonders hesindegläubig':'7-5',
'Besonders firungläubig':'9-8',
'Besonders tsagläubig':'10',
'Besonders tsagläubig':'1',
'Besonders perainegläubig':'6-2',
'Besonders ingerimmgläubig':'9-7',
'Besonders rahjagläubig':'10',
'Besonders rahjagläubig':'1',
'Besonders ifirngläubig':'2',
'Besonders nandusgläubig':'3',
'Besonders korgläubig':'4',
'Besonders avesgläubig':'6-5',
'Glaubt  an  einen  bestimmten Heiligen':'8-7',
'Glaubt  an  eine  bestimmte Heilige':'10-9',
'Hatte  schon  mit  vielen geschlafen':'3-1',
'Jungfrau/-mann':'5-4',
'Lebt  in  einer  stürmischen Beziehung':'8-6',
'Lebt  in  einer  harmonischen Beziehung':'10-9',
'Lebt  in  einer  harmonischen Beziehung':'1',
'wird vom Partner betrogen':'4-2',
'Modebewusst':'8-5',
'Verfügt über Geheimwissen':'10-9',
'Dichtet gerne':'3-1',
'Singt gerne':'8-4',
'Kennt viele Sagen':'10-9',
'Kennt viele Sagen':'3-1',
'Kennt viele Lieder':'7-4',
'Kennt viele Gerüchte':'10-8',
'Kennt viele Gerüchte':'2-1',
'Viel gereist':'3-1',
'Wäre gern ein Magier':'4',
'Kauft immer zuviel ein':'6-5',
'Hortet allerlei Dinge':'8-7',
'Erwartet den Weltuntergang':'10-9',
'Wird von jedem geärgert':'4-1',
'Wird von jedem gemocht':'8-5',
'Einbildungen':'10-9',
'Wahnideen':'1',
'Liebt Vögel':'4-2',
'Liebt Tiere':'7-5',
'Liebt Katzen':'10-8',
'Liebt Hunde':'3-1',
'Liebt Pferde':'6-4',
'Liebt Pflanzen und Bäume':'8-7',
'Liebt Süßes':'10-9',
'Liebt Süßes':'1',
'Liebt Saures':'4-2',
'Liebt scharfes Essen':'6-5',
'Hasst Vögel':'10-7',
'Hasst Tiere':'3-1',
'Hasst Katzen':'6-4',
'Hasst Hunde':'9-7',
'Hasst Pferde':'10',
'Hasst Pferde':'2-1',
'Hasst Pflanzen und Bäume':'4-3',
'Hasst Süßes':'6-5',
'Hasst Saures':'9-7',
'Hasst scharfes Essen':'10',
'Hasst scharfes Essen':'1',
'mohischer Abstammung':'3-2',
'elfischer Abstammung':'7-4',
'Vorfahren waren adelig':'9-8',
'Sympatisiert  mit  Borbard(s Erben)':'10',
'Sympatisiert  mit  Borbard(s Erben)':'1',
'Wurde  von  einem  Dämon versucht':'3-2',
'Wird  von  einem  Dämon versucht':'4',
'Großes Schlafbedürfnis':'8-5',
'Geringes Schlafbedürfnis':'10-9',
'Geringes Schlafbedürfnis':'2-1',
'Hält immer Mittagsschlaf':'4-3',
'Ortskundig':'8-5',
'Erfolgsgewöhnt':'10-9',
'Erfolgsgewöhnt':'2-1',
'Misserfolgsgewöhnt':'6-3',
'Einzelkind':'8-7',
'Musste  schon  früh  für Geschwister sorgen':'10-9',
'Musste  schon  früh  für Geschwister sorgen':'1',
'Bei den Großeltern aufgewachsen':'4-2',
'Bei Verwandten aufgewachsen':'6-5',
'Kann gut zuhören':'10-7',
'Hört nie richtig zu':'2-1',
'Will es allen recht machen':'4-3',
'Hasst Kompromisse':'6-5',
'Kennt  sich  mit  dem  anderen Geschlecht aus':'8-17',
'Kennt  sich  mit  dem  anderen Geschlecht nicht aus':'10-9',
'Pervers':'1',
'Hat eine fixe Idee':'3-2',
'Zahnschmerzen':'6-4',
'chronische Kopfschmerzen':'8-7',
'chronische Rückenschmerzen':'10-9',
'Blähungen':'3-1',
'Hat  große  Schuld  auf  sich geladen':'5-4',
'Wetterfühlig':'9-6',
'Besitzt ein magisches Artefakt':'10',
'Besaß ein magisches Artefakt':'1',
'Besitzt  ein  Haus  (über  seinem Stand)':'3-2',
'Will  unbedingt  in  höheren Stand aufsteigen':'5-4',
'Vorurteile  gegenüber Geweihten':'6',
'Vorurteile  gegenüber Südländern':'7',
'Vorurteile gegenüber Elfen':'10-8',
'Vorurteile gegenüber Zwergen':'3-1',
'Vorurteile  gegenüber Magiekundigen':'7-4',
'Vorurteile  gegenüber Fahrendem Volk':'10-8',
'Begnadete(r) Tänzer(in)':'1',
'Begnadete(r) Sänger(in)':'2',
'Begnadete(r) Maler(in)':'3',
'Begnadete(r) Zeichner(in)':'4',
'Imman-Fan':'6-5',
'Turnier-Fan':'9-7',
'Turnier-Fan':'10',
'Schaukampf-Fan':'3-1',
'Hat geheimen Rückzugsort':'4',
'Weint manchmal ohne Grund':'5',
'Will  nie  einen  Gefallen annehmen':'7-6',
'Will niemanden etwas schuldig sein':'9-8',
'Betätigt sich gerne körperlich':'10',
'Betätigt sich gerne körperlich':'2-1',
'Betätigt  sich  nicht  gerne körperlich':'5-3',
'Naturmensch':'8-6',
'Glaubt  dass  alle  Menschen lügen':'9',
'Lässt gerne Steinchen auf dem Wasser springen':'9'
}