darstellung_temp = {'Hochgezogene Schulter':'1',
'Hängende Schultern':'2',
'Schultern gelegentlich leicht kreisen':'3',
'Verdrehter  Oberkörper  (dem  Partner nicht zugewandt)':'4',
'Dezent  dem  Gegenüber  die  Muskeln zeigen':'5',
'Sich andauernd strecken':'6',
'Andauernd „den Hals einrecken“':'7',
'Mit dem Kopf hin- und herwackeln':'8',
'Sich immer wieder anders hinsetzen':'9',
'Sagt immer „Wa?“ am Ende des Satzes':'10',
'Sagt immer „Ne?“ am Ende des Satzes':'1',
'Sagt immer „Nh.“ am Ende des Satzes':'2',
'Sagt immer „Nichwar?“':'3',
'Macht immer „Pfff“':'4',
'Sagt immer „Hm hm…“':'5',
'Sagt immer „Ja ja, so is das…“':'6',
'Sagt immer „Jo jo.“':'7',
'Sagt immer „Schlimm schlimm…“':'8',
'Sagt immer „...ich mein..."':'9',
'Spricht nur in kurzen Sätzen':'10',
'Spricht in ausschweifenden Sätzen':'1',
'Spricht sehr monoton':'2',
'Spricht mit falscher Betonung':'3',
'Betont immer das „t“':'4',
'Betont deutlich Vokale':'5',
'Betont immer das Ende von Wörtern':'6',
'Betont sehr stark („Misssster Aaaannnnderson…“)':'7',
'Macht Pausen nach Sätzen':'8',
'Macht Pausen in Sätzen':'9',
'Sagt oft „äh“':'10',
'Sagt oft „öh“':'1',
'Sagt oft „ähem“':'2',
'Sagt oft „Weißte?“':'3',
'Sagt oft „Verstehste?“':'4',
'Bellt mehr, als dass er spricht':'5',
'Spricht mit gepresster Stimme':'6',
'Lispelt':'7',
'Lispelt sehr stark':'8',
'Nuschelt':'9',
'Nuschelt sehr stark':'10',
'Spricht durch die Nase':'1',
'Spricht mit tiefem Bass':'2',
'Spricht mit hoher Stimme':'3',
'Spricht mit warmer Stimme':'4',
'Spricht mit kühler Stimme':'5',
'Wiederholt sich andauernd':'6',
'Hat von Grammatik keine Ahnung':'7',
'Lacht wie ein Pferd':'8',
'Lacht wie eine Hyäne':'9',
'Lacht keifend':'10',
'Lacht laut und aufdringlich':'1',
'Lacht heiser (Hrhrhr!)':'2',
'Beim Sprechen versuchen möglichst wenig den Mund zu bewegen':'3',
'Beim  Sprechen  versuchen  den  Mund rund zu machen':'4',
'Beim  Sprechen  versuchen  die  Zähne  zu zeigen':'5',
'Mit schiefem Mund sprechen':'6',
'Augen schließen wenn man spricht, immer nur kurz aufmachen':'7',
'Augen zukneifen beim Sprechen':'8',
'Augen stark zukneifen beim Sprechen':'9',
'Schmatzgeräusche beim Sprechen':'10',
'Stark Luft holen am Satzanfang':'1',
'Sprechen  als  ob  die  Luft  aus  einem hinausstörmt,  dann  wieder  kräftig  Luft holen, etc.':'2',
'Zu Boden schauen beim sprechen':'3',
'Schnell sprechen':'4',
'Bei  schnellen  sprechen  sich  immer umschauen,  als  ob  man  sich  gegenüber unsichtbaren  Zuhörern  rechtfertigen müsse':'5',
'Oft nicken beim sprechen':'6',
'Oft den Kopf schütteln beim sprechen':'7',
'Gelegentlich auf Unterarm trommeln':'8',
'Unterarme reiben':'9',
'Den Kopf schräg legen beim sprechen':'10',
'Unterlippe hervor schieben beim Sprechen':'1',
'Schiefen Mund machen':'2',
'Runden Mund machen':'3',
'Untere Zahnreihe zeigen':'4',
'Obere Zahnreihe zeigen':'5',
'Auf Unterlippe beißen':'6',
'Auf Unterlippe rumkauen':'7',
'Auf Oberlippe rumkauen':'8',
'Lippen befeuchten':'9',
'Zähne zusammenpressen':'10',
'Augen zukneifen':'1',
'Augen weiten':'2',
'Kurzzeitig schielen':'3',
'Viel blinzeln':'4',
'Immer wieder seufzen':'5',
'Untere Augenlider nach oben schieben':'6',
'Nasenflügel weiten':'7',
'Stirn runzeln':'8',
'Augenbrauen zusammenziehen':'9',
'Augenbrauen heben':'10',
'Nur eine Augenbraue heben':'11',
'Ein Auge nervös zucken lassen':'2',
'Den  Gegenüber  nur  mit  einem  Auge anschauen (d.h. im nicht das volle Gesicht zuwenden)':'3',
'Nicht den Gegenüber fixieren / Blick ins Leere':'3',
'In den Ausschnitt-starren :-)':'4',
'In die Augen starren':'5',
'Auf den Mund starren':'6',
'Auf die Ohren starren':'7',
'Finster  dreinblicken  (Kopf  nach  unten neigen  aber  immer  noch  in  die  Augen schauen)':'8',
'Kinn reiben':'9',
'Kinn kratzen':'10',
'Kinn kneifen':'11',
'Kinn mit dem Finger beklopfen':'2',
'Oberlippe reiben':'3',
'Oberlippe kratzen':'4',
'Oberlippe kneifen':'5',
'Oberlippe mit dem Finger beklopfen':'6',
'Unterlippe reiben':'7',
'Unterlippe kratzen':'8',
'Unterlippe kneifen':'9',
'Unterlippe mit dem Finger beklopfen':'10',
'Auf Wangeninnenseite kauen':'11',
'Wange reiben':'2',
'Wange kratzen':'3',
'Wange kneifen':'4',
'Wange mit dem Finger beklopfen':'5',
'Nase reiben':'6',
'Nase kratzen':'7',
'Nase kneifen':'8',
'Nase mit dem Finger beklopfen':'9',
'Stirn reiben':'10',
'Stirn kratzen':'11',
'Stirn kneifen':'2',
'Stirn mit dem Finger beklopfen':'3',
'Ohr reiben':'4',
'Ohr kratzen':'5',
'Ohr kneifen':'6',
'Ohr mit dem Finger beklopfen':'7',
'Haare verzwirbeln':'8',
'Haare nach oben ziehen':'9',
'Haare nach hinten streichen':'10',
'Strähne aus dem Gesicht streichen':'11',
'Strähne (von mir aus auch imaginäre) aus dem Gesicht pusten':'2',
'„Bart“ streichen':'3',
'„Bart“ zwirbeln“':'4',
'Etwas aus dem „Bart“ holen':'5',
'Gesicht aufstützen':'6',
'Sich auf dem Stuhl abstützen':'7',
'Gesicht mit beiden Händen reiben':'8',
'Mit den Fingern in den Zähnen bohren':'9',
'Mit der Zunge in den Zahnlücken nach Essensresten bohren':'10',
'Backen leicht aufblasen':'11',
'Sich über den Hals streichen':'2',
'Hand auf die Brust legen':'3',
'Hände vor Gesicht falten':'4',
'Hände vor Bauch falten':'5',
'Hände reiben ("Ausgezeichnet, Smithers…")':'6',
'Mit dem Finger ins Leer deuten':'7',
'Ausladende Gesten':'8',
'Mit Gesten die ganze Welt umfassen':'9',
'Affektierte Gesten':'10',
'Mit den Knöcheln der einen Hand gegen die Ballen der anderen Klopfen':'11',
'Knöchel aneinander schlagen':'2',
'Mit den Fingernägeln knispeln':'3',
'An den Fingernägeln kauen':'4',
'An den Fingernägeln kauen, es aber dann gleich wieder lassen… dann wieder':'5',
'Mundwinkel nach unten ziehen (Merkel-  Gesicht)':'6',
'Schneidezähne möglichst immer zeigen':'7',
'Hasenzähne imitieren':'9',
'Handrücken reiben':'10',
'Durch Zähne atmen':'11',
'Mit dem Fuß auf den Boden klopfen':'2',
'Mit dem Fuß über den Boden streichen':'3',
'Mit dem Fuß über den Boden kratzen':'4',
'Gegenüber oft ins Wort fallen':'5',
'Wenn Gegenüber spricht oft nicken':'6',
'Wenn  Gegenüber  spricht  oft  die  Stirn runzeln':'7',
'Wenn  Gegenüber  spricht  nur  halb hinhören':'8',
'Wenn Gegenüber spricht oft seufzen':'9',
'Sehr leise wiederholen was der Gegenüber sagt':'10',
'So  lange  sprechen  bis  man  keine  Luft hat, dann ausführlich Luft holen':'11',
'Beim Sprechen immer falsch einatmen':'2',
'Gegenüber  immer  den  Satz  vollenden lassen':'3',
'Keinen Satz vollenden sondern mittendrin einen neuen beginnen':'4',
'Spricht unangenehm langsam':'5',
'Sich dem Gegenüber entgegen lehnen':'6',
'Auf Stuhl wippen':'7',
'Immer leicht verzweifelt dreinblicken':'8',
'Hals vorne massieren':'9',
'Hals hinten massieren':'10',
'Dezent  Linien  auf  das  eigene  Gesicht malen':'11',
'Beim Sprechen möglichst Gesichtsmuskeln anspannen':'2',
'Komische Handgesten machen':'3',
'Daumen umeinander kreisen lassen':'4',
'Versuchen sich einen scheitel zu machen':'5',
'Sich immer was aus dem Auge holen':'6',
'Augen reiben':'7',
'An eigenen Ohren ziehen':'8',
'Ohr(en) massieren':'9',
'Gelegentlich auf Stuhl trommeln':'10',
'Käptn Jack Sparrow nachahmen':'21',
'Zusammengesunken sitzen':'2',
'Kerzengerade sitzen':'3',
'Schief sitzen':'4',
'Italienische Handgesten':'5',
'Mund leicht offen lassen':'6',
'Dezent  so  tun  als  ob  ein  Tierchen  auf einem krabbelt':'7',
'Staub von Dinge wischen':'8',
'Sich selbst abbürsten':'9',
  'Oft schlucken':'9' }