gesichtsmerkmal_temp = {
'Fließende Stirn':'2-1',
'Hohe Stirn':'6-3',
'Buschige Augenbrauen':'3-1',
'Augenbraunen  mit  langen Haaren':'4-3',
'Geschwungene Augenbrauen':'6-5',
'Stark geschwungene Augenbrauen':'2-1',
'Sehr feine Augenbrauen':'4-3',
'Sehr kleine Augenbrauen':'6-5',
'Schräge Augenbrauen':'2-1',
'Balkenaugenbraue  (sog. „Unibrow“)':'4-3',
'Keine Augenbrauen':'6-5',
'Große Augen':'3-1',
'Wirklich grooooße Rehaugen':'4',
'Kleine Schweineaugen':'6-5',
'Schräge  und  große  Augen (elfischer Einschlag)':'2-1',
'Verkniffene Augen':'4-3',
'Zugeschwollene Augen ':'6-5',
'Hundeblick':'2-1',
'Schräge Augen':'4-3',
'Silberblick':'5',
'Wanderndes Auge':'6',
'Mandelaugen':'3-1',
'Große Mandelaugen':'5-4',
'Schlafzimmerblick':'6-5',
'Tränende Augen':'6',
'Eklig lange Nasenhaare':'1',
'Immer  nur  halbgeöffnete Augen':'4-3',
'Lange Augenlider':'6-5',
'Glitzernde verzaubernde Augen':'2-1',
'Arroganter Blick':'5-2',
'platte Nase':'6',
'Stupsnase':'3-1',
'Hakennase':'6-4',
'Adlernase':'3-1',
'Sehr feine Nase ':'6-4',
'Spitze Nase':'3-1',
'Knollennase':'6-4',
'Riiiiiiesenzinken':'1',
'Klassische Nase':'2',
'Sehr breite Nase':'3',
'Sehr schlanke Nase':'4',
'Gebrochene  und  gut  geheilte Nase':'5',
'Gebrochene  und  schlecht geheilte Nase (schief)':'6',
'Hasenscharte':'1',
'Ausgeprägte Hasenscharte':'2',
'Narbe auf der Wange':'3',
'Narbe auf der Stirn':'4',
'Narbe am Kinn ':'5',
'Schmollmund':'6',
'Angelina-Jolie-Mund':'2-1',
'Dünne Lippen':'4-3',
'Große Unterlippe':'6-5',
'Kleiner Mund':'2-1',
'Kleiner voller Mund ':'1',
'Breiter Mund':'4-3',
'Rissige Lippen':'6-5',
'Dunkelrote Lippen':'2-1',
'Dünne Unterlippe':'4-3',
'Kleiner voller Mund':'5',
'Kirschmund ':'6',
'Breiter schmaler Mund':'1',
'Blutleere Lippen':'2',
'Zwei große Hasenzähne':'4-3',
'Zahnlücke':'6-5',
'Große Zahnlücke':'2-1',
'kleine Zahnlücke':'4-3',
'Schiefe Zähne':'6-5',
'Fehlender Schneidezahn (oben)':'1',
'Fehlender Schneidezahn (unten)':'2',
'Fehlender Eckzahn (oben)':'3',
'Fehlender Eckzahn (unten)':'4',
'Braune Zähne':'5',
'Schwarze Zähne':'6',
'Einige  Schwarze  zähne':'1',
'Gelbe Zähne':'4-2',
'Gute Zähne':'5',
'Strahlend weiße Zähne':'6',
'Grübchen':'1',
'Schmales Gesicht':'2',
'Fast Dreieckiges Gesicht':'3',
'Rundes Gesicht':'5-4',
'Langes Gesicht':'6',
'Kräftige Wangenknochen':'3-1',
'Hageres Gesicht':'4-3',
'Fehlendes Ohr ':'6-5',
'Leichte Blumenkohlohren':'1',
'Kleine Ohren':'3-2',
'Blumenkohlohren':'5-4',
'Leicht spitze Ohren':'6-5',
'Spitzes Kinn':'2-1',
'Kräftiges Kinn':'4-3',
'Kantiges-Kinn':'6-5',
'Kinn  mit  ausgeprägtem Grübchen':'2-1',
'Eckiges Kinn':'4-3',
'Fließendes Kinn':'6-5',
'Grübchen':'2-1',
'Schmales Gesicht':'4-3',
'Breites Gesicht':'6-5',
'Langes Gesicht':'1',
'Segelohren':'3-2',
'leichte Segelohren':'6-4',
'Große Ohren':'2-1',
'vorspringenede Kinn':'4-3',
'Michael-Schumacher-Kinn ':'6-5',
'Langes Gesicht':'6',
'Hageres Gesicht':'2',
'Kleine Ohren ':'6',
'Leichte Blumenkohlohren':'1',
'Leicht spitze Ohren':'2',
'Spitzes Kinn':'3',
'Kräftiges Kinn':'4',
'Michael-Schumacher-Kinn':'5',
'Kantiges Kinn':'6',
'Kinn  mit  ausgeprägtem Grübchen':'1',
'Eckiges Kinn':'2',
'Fließendes Kinn':'3',
'Herpesbläschen':'4',
'Warze an der Wange':'5',
'Warze an der Nase':'6',
'Warze an der Augenbraue':'1',
'Warze an der Oberlippe':'2',
'Warze am Kinn':'3',
'Warzen':'4',
'Großer  Leberfleck  an  der Wange':'5',
'Großer  Leberfleck  an  der Nase':'6',
'Großer  Leberfleck  an  der Augenbraue':'1',
'Großer  Leberfleck  an  der Oberlippe':'2',
'Großer Leberfleck am Kinn':'3',
'viele Muttermale':'4',
'Große Poren':'6-5',
'Viele Sommersprossen':'3-1',
'Sehr rosiger Teint':'4',
'Kleine Äderchen auf Nase und Wangen':'5',
'Hautanomalie (dunkle und helle Flecken)':'6',
'Pockennarbiges Gesicht':'1',
'Stellenweise Aknenarben':'2',
'Pockennarbiges Gesicht':'3',
'Stellenweise Aknenarben':'4',
'Viele Aknenarben':'5',
'Fettige Haut ':'6',
'Mitesser':'2-1',
'Viele Mitesser':'4-3',
'Pickel':'6-5',
'Viele Pickel':'2-1',
'Fettige Haut':'4-3',
'Ausschlag':'6-5',
'Dunkler Teint':'3-1',
'Bleicher Teint':'6-4',
'Dunkler Teint':'3-1',
'Sehr dunkler Teint':'5-4',
'Kleine  Tätowierung  im Gesicht':'6',
'Lachfältchen':'3-1',
'Sorgenfalten ':'6-4',
'Makellose Haut':'2-1',
'Denkfalten auf der Stirn ':'6-3',
'Falte zwischen den Augen':'2-1',
'Faltenlos':'5',
'Falten um die Nase':'6',
'Augen weit auseinander ':'1',
'Augen nah beieinander':'2',
'Höckernase':'4-3',
'leichte Höckernase':'6-5',
'deutlicher Überbiss':'2-1',
'Breites Lächeln':'3',
'klassisches Gesicht':'6-4',
'gutaussehend':'4-1',
'bildschön':'5',
'urhässlich':'6',
'unansehnlich':'4-1',
'Glubschaugen':'6-5',
'tiefe Augen':'1',
'attraktive Wangenknochen':'2',
'hässlich ':'6-3',
'sehr gutaussehend':'3-1',
'attraktiver Mund':'5-3',
'sehr kurze Nase':'4',
'deutlicher Überbiss':'2-1',
'markanter Kopf':'4-3',
'breites Lächeln':'6-5',
'sehr gutaussehend':'1',
'bildschön':'2',
'urhässlich':'3',
'tiefe Augen':'5-4',
'Glubschaugen':'6',
'ebenmäßiges Gesicht':'2-1',
'ehrliches Lächeln':'3',
'verkniffenes Lächeln':'4',
'Schiefes Lächeln':'6-5',
'spitzbübisches Gesicht':'2-1',
'Bulldoggen Gesicht':'4-3',
'Fuchsgesicht':'6-5',
'Krötengesicht':'2-1',
'Wolfsgesicht':'4-3',
'wachsame Augen ':'6-5',
'bezaubernde Nase':'11',
'kindliches Gesicht':'4-2',
'kleiner Kopf':'6-5',
'reifes Gesicht':'3-1',
'lange Nase':'4-3',
'schöne Augenbrauen':'6-5',
'großer Kopf':'2-1',
'langer Hals':'5-3',
'schiefe Nase':'6',
'kurzer Hals':'3-1',
'unsymmetrisches Gesicht':'4',
'irrer Blick':'5',
'quadratisches Grinsen':'6',
'schiefes Grinsen':'1',
'relativ  frische  Wunde  an  der Stirn':'2',
'relativ  frische  Wunde  an  der Nase':'3',
'relativ frische Wunde am Ohr':'4',
'relativ  frische  Wunde  am Mund':'5',
'relativ frische Wunde am Kinn':'6',
'relativ  frische  Wunde  an  der Wange':'1',
'Vierschrötig':'3-2',
'Bärengesicht':'4',
'Maskengesicht':'5',
'Lebhaftes Gesicht':'6'
}