
Haartracht_w_temp = {'Igelfrisur':'2-1',
'Seitenscheitel, kurz':'6-3',
'Seitenscheitel, schlecht geschnitten':'8-7',
'Mittelscheitel, kurz':'10-9',
'Mittelscheitel, kurz':'2-1',
'Mittelscheitel, schlecht geschnitten':'4-3',
'Seitenscheitel, schlecht geschnitten':'5',
'Mittelscheitel, schlecht geschnitten (Fransen)':'6',
'Seitenscheitel, an den Schläfen kurz rasiert':'8-7',
'Mittelscheitel, an den Schläfen kurz rasiert':'10-9',
'Seitenscheitel, schlecht geschnitten, an den Schläfen kurz rasiert':'1',
'Mittelscheitel, schlecht geschnitten, an den Schläfen kurz rasiert':'2',
'Prinz-Eisenherz-Frisur':'5-3',
'gezähmte Lockenpracht, lang':'7-6',
'Lockenpracht, lang':'10-8',
'Lockenpracht, lang':'1',
'ungezähmte Lockenpracht, lang':'3-2',
'ungezähmter Lockenkopf, mittellang':'5-4',
'Lockenkopf, mittellang':'10-5',
'Lockenpracht, unter Kopftuch':'1',
'ungezähmter Lockenkopf, kurz':'2',
'Lockenkopf, kurz':'6-3',
'Mittellange Haare (bis Kinn), ins Gesicht fallend':'9-7',
'Mittellange Haare (bis Kinn), Pony':'10',
'Mittellange Haare (bis Kinn), Pony':'2-1',
'Mittellange Haare (bis Kinn), gescheitelt':'5-3',
'Mittellange Haare (bis Kinn), Mittelscheitel':'8-6',
'Mittellange Haare (bis Kinn), Haarreif':'10-9',
'Mittellange Haare (bis Kinn), Haarreif':'1',
'Mittellange Haare (bis Kinn), nach hinten gekämmt':'4-2',
'Mittellange Haare (bis Kinn), unter Kopftuch':'7-5',
'Mittellange Haare (bis Kinn), mit Haarspange':'10-8',
'Mittellange Haare (bis Kinn), mit Haarband':'3-1',
'Mittellange Haare (bis Kinn), mit Haarbändern':'6-4',
'Mittellange Haare (bis Kinn), dicker Zopf':'9-7',
'Mittellange Haare (bis Kinn), zwei Zöpfe':'10',
'Mittellange Haare (bis Kinn), zwei Zöpfe':'2-1',
'Mittellange Haare (bis Kinn), viele Zöpfe':'5-3',
'Zöpfe mit Haarnadeln am Kopf befestigt':'8-6',
'Mittellange Haare (bis Kinn), unter Kopftuch':'10-9',
'Mittellange Haare (bis Kinn), unter Kopftuch':'1',
'Mittellange Haare (bis Kinn), unter Haube':'4-2',
'Mittellange gewellte Haare (bis Kinn), ins Gesicht fallend':'7-5',
'Mittellange gewellte Haare (bis Kinn), gescheitelt':'10-8',
'Mittellange gewellte Haare (bis Kinn), Pony':'3-1',
'Mittellange gewellte Haare (bis Kinn), Mittelscheitel':'6-4',
'Mittellange gewellte Haare (bis Kinn), Haarreif':'9-7',
'Mittellange gewellte Haare (bis Kinn), Haarspange':'10',
'Mittellange gewellte Haare (bis Kinn), Haarspange':'2-1',
'Mittellange gewellte Haare (bis Kinn), Haarband':'5-3',
'Mittellange gewellte Haare (bis Kinn), Haarbänder':'8-6',
'Lange Haare (Schulterlang), ins Gesicht fallend':'10-9',
'Lange Haare (Schulterlang), ins Gesicht fallend':'1',
'Lange Haare (Schulterlang), gescheitelt':'4-2',
'Lange Haare (Schulterlang), nach hinten gekämmt':'7-5',
'Lange Haare (Schulterlang), mit Haarband zusammengehalten':'10-8',
'Lange Haare (Schulterlang), mit zwei Haarbändern links und rechts':'3-1',
'Lange Haare (Schulterlang), Pony':'6-4',
'Lange Haare (Schulterlang), Zöpfe mit Haarnadeln am Kopf befestigt':'9-7',
'Lange Haare (Schulterlang), Haarreif':'10',
'Lange Haare (Schulterlang), Haarreif':'2-1',
'Lange Haare (Schulterlang), Haarspange':'5-3',
'Lange Haare (Schulterlang), Haarbänder':'8-6',
'Lange Haare (Schulterlang), Mittelscheitel':'10-9',
'Lange Haare (Schulterlang), Mittelscheitel':'1',
'Lange Haare gewellte (Schulterlang), ins Gesicht fallend':'4-2',
'Lange Haare gewellte (Schulterlang), gescheitelt':'7-5',
'Lange Haare gewellte Schulterlang), nach hinten gekämmt':'10-8',
'Lange Haare gewellte (Schulterlang), mit Haarband zusammengehalten':'3-1',
'Lange Haare gewellte (Schulterlang), mit zwei Haarbändern links und rechts':'6-4',
'Lange Haare gewellte (Schulterlang), Pony':'9-7',
'Lange Haare gewellte (Schulterlang), Zöpfe mit Haarnadeln am Kopf befestigt':'10',
'Lange Haare gewellte (Schulterlang), Zöpfe mit Haarnadeln am Kopf befestigt':'2-1',
'Lange Haare gewellte (Schulterlang), Haarreif':'5-3',
'Lange Haare gewellte (Schulterlang), Haarspange':'8-6',
'Lange Haare gewellte (Schulterlang), Haarbänder':'10-9',
'Lange Haare gewellte (Schulterlang), Haarbänder':'1',
'Lange Haare gewellte (Schulterlang), Mittelscheitel':'4-2',
'Lange Haare (bis Rücken), ins Gesicht fallend':'7-5',
'Lange Haare (bis Rücken), gescheitelt':'10-8',
'Lange Haare (bis Rücken), nach hinten gekämmt':'3-1',
'Lange Haare (bis Rücken), mit Haarband zusammengehalten':'6-4',
'Lange Haare (bis Rücken), mit zwei Haarbändern links und rechts':'9-7',
'Lange Haare (bis Rücken), Pony':'10',
'Lange Haare (bis Rücken), Pony':'2-1',
'Lange Haare (bis Rücken), Zöpfe mit Haarnadeln am Kopf befestigt':'5-3',
'Lange Haare (bis Rücken), Mittelscheitel':'8-6',
'Lange Haare (bis Rücken), Haarreif':'10-9',
'Lange Haare (bis Rücken), Haarreif':'1',
'Lange Haare (bis Rücken), Haarspange':'4-2',
'Lange Haare (bis Rücken), Haarspangen':'7-5',
'Lange Haare gewellte (bis Rücken), ins Gesicht fallend':'10-8',
'Lange Haare gewellte (bis Rücken), gescheitelt':'3-1',
'Lange Haare gewellte (bis Rücken), nach hinten gekämmt':'6-4',
'Lange Haare gewellte (bis Rücken), mit Haarband zusammengehalten':'9-7',
'Lange Haare gewellte (bis Rücken), mit zwei Haarbändern links und rechts':'10',
'Lange Haare gewellte (bis Rücken), mit zwei Haarbändern links und rechts':'2-1',
'Lange Haare gewellte (bis Rücken), Pony':'5-3',
'Lange Haare gewellte (bis Rücken), Zöpfe mit Haarnadeln am Kopf befestigt':'8-6',
'Lange Haare gewellte (bis Rücken), Haarreif':'10-9',
'Lange Haare gewellte (bis Rücken), Haarreif':'1',
'Lange Haare gewellte (bis Rücken), Haarspange':'4-2',
'Lange Haare gewellte (bis Rücken), Haarspangen':'7-5',
'Lange Haare gewellte (Schulterlang), unter Kopftuch':'8',
'Lange Haare, Dutt am Hinterkopf':'10-9',
'Lange Haare, Dutt rausfallende Strähnen':'2-1',
'Lange Haare, Dutt oben':'4-3',
'Lange Haare, Prinzessin-Leia- Gedächtnisfrisur':'6-5',
'Lange Haare, Zopf kunstvoll um den Kopf gewickelt':'8-7',
'Lange Haare, kunstvoll aufgetürmt':'9',
'Lange Haare, mit vielen Bändchen zusammengehalten':'10',
'Lange Haare (Schulterlang), viele Zöpfe':'1',
'Lange Haare, mit vielen Bändchen zusammengehalten':'2',
'Mittellange Haare mit mittels Brennschere erzeugten Locken':'3',
'Kurze Haare mit Fett nach hinten gestylt':'5-4',
'Mittellange Haare mit Fett nach hinten gestylt':'7-6',
'Lange Haare mit Fett nach hinten gestylt':'9-8',
'Lange Haare mit Fett nach hinten gestylt':'10',
'Lange gewellte Haare (Schulterlang), Haarband':'3-1',
'Lange Haare (Schulterlang), Stirnband':'6-4',
'Lange gewellte Haare (Schulterlang), Stirnband':'8-7',
'Lange gewellte Haare (Schulterlang), Haarband':'9',
'Lange Haare (Schulterlang), hinters Ohr geklemmt':'10',
'Lange Haare (Schulterlang), hinters Ohr geklemmt':'2-1',
'Lange gewellte Haare (Schulterlang), hinters Ohr geklemmt':'4-3',
'Lange Haare (bis Rücken), hinters Ohr geklemmt':'7-5',
'Sehr lange Haare (bis Hüfte)':'8',
'Sehr lange Haare (bis Hüfte) Pony':'9',
'Sehr lange Haare (bis Hüfte) gewellt':'10'}

Haartracht_m_temp = {'Glatze (durch Haarausfall)':'3-1',
'Glatze (rasiert)':'7-4',
'Glatze mit ein paar Haarfuseln, welche wild nach oben stehen':'9-8',
'Halbglatze kurz':'13-10',
'Halbglatze, mittellang':'19-14',
'Halbglatze, lange Haare':'20',
'Halbglatze, lange Haare':'1',
'Halbglatze, Zopf':'4-2',
'Halbglatze mit über den Schädel gekämmten Haaren':'8-5',
'Stirnglatz Rest kurz':'10-9',
'Stirnglatz Rest mittellang':'12-11',
'Stirnglatz Rest lang':'14-13',
'Geheimratsecken, Rest kurz':'18-15',
'Geheimratsecken, Rest mittellang':'20-19',
'Geheimratsecken, Rest mittellang':'2-1',
'Geheimratsecken, Rest lang':'5-3',
'Geheimratsecken, Rest Zopf':'7-6',
'Geheimratsecken, Rest Haarband':'9-8',
'Starke Geheimratsecken, Rest Zopf':'10',
'Starke Geheimratsecken, Rest kurz':'12-11',
'Starke Geheimratsecken, Rest mittellang':'14-13',
'Starke Geheimratsecken, Rest lang':'15',
'Starke Geheimratsecken, Rest Haarband':'16',
'Kurz rasiert':'19-17',
'Kurz rasiert (unregelmäßig)':'20',
'Kurz rasiert, Zopf am Hinterkopf':'1',
'Kurz, schlecht geschnitten (Fransen)':'2',
'Sehr kurz':'6-3',
'Igel-Frisur':'11-7',
'Igel-Frisur, Zopf am Hinterkopf':'12',
'Seitenscheitel':'15-13',
'Seitenscheitel, schlecht geschnitten (Fransen)':'17-16',
'Mittelscheitel':'20-18',
'Mittelscheitel, schlecht geschnitten (Fransen)':'3-1',
'Seitenscheitel, an den Schläfen kurz rasiert':'6-4',
'Seitenscheitel, schlecht geschnitten (Fransen), an den Schläfen kurz rasiert':'8-7',
'Mittelscheitel, an den Schläfen kurz rasiert':'11-9',
'Mittelscheitel, schlecht geschnitten (Fransen), an den Schläfen kurz rasiert':'13-12',
'Seitenscheitel, schlecht geschnitten (Fransen)':'15-14',
'Seitenscheitel, an den Schläfen kurz rasiert':'18-16',
'Seitenscheitel, schlecht geschnitten (Fransen), an den Schläfen kurz rasiert':'20-19',
'Mittelscheitel, an den Schläfen kurz rasiert':'3-1',
'Prinz-Eisenherz-Frisur':'9-4',
'Topffrisur':'17-10',
'Lockenkopf, kurz':'20-18',
'Lockenkopf, kurz':'1',
'Lockenkopf, mittellang':'5-2',
'Mittellange Haare (bis Kinn), Pony':'7-6',
'Mittellange Haare (bis Kinn), nach hinten gekämmt':'9-8',
'Mittellange Haare (bis Kinn), Mittelscheitel':'13-10',
'Mittellange Haare (bis Kinn), gescheitelt':'19-14',
'Mittellange Haare (bis Kinn), ins Gesicht fallend':'20',
'Mittellange Haare (bis Kinn), ins Gesicht fallend':'1',
'Mittellange Haare (bis Kinn), Zöpfe an den Schläfen':'3-2',
'Mittellange gewellte Haare (bis Kinn), ins Gesicht fallend':'4',
'Mittellange gewellte Haare (bis Kinn), Mittelscheitel':'7-5',
'Mittellange gewellte Haare (bis Kinn), Pony':'9-8',
'Mittellange gewellte Haare (bis Kinn), Haarreif':'11-10',
'Lange Haare (Schulterlang), ins Gesicht fallend':'12',
'Lange Haare (Schulterlang), gescheitelt':'14-13',
'Lange Haare (Schulterlang), Zöpfe an den Schläfen':'15',
'Lange Haare (Schulterlang), nach hinten gekämmt':'16',
'Lange Haare (Schulterlang), mit Haarband zusammengehalten':'18-17',
'Lange Haare (Schulterlang), mit Haarspange zusammengehalten':'19',
'Lange Haare (Schulterlang), mit Haarreif':'20',
'Lange Haare (Schulterlang), mit Haarreif':'1',
'Lange Haare (Schulterlang), Stirnband':'2',
'Lange Haare (Schulterlang), Pony':'3',
'Lange gewellte Haare (Schulterlang), mit Haarband zusammengehalten':'4',
'Lange gewellte Haare (Schulterlang), gescheitelt':'6-5',
'Lange gewellte Haare (Schulterlang), Stirnband':'7',
'Lange Haare (Schulterlang), viele Zöpfe':'8',
'Vorne kurz, hinten lang (Vokuhila)':'13-9',
'Vorne kurz, hinten lang (Vokuhila) kombiniert mit Halbglatze':'15-14',
'Kurze Haare mit Fett nach hinten gestylt':'17-16',
'Mittellange Haare mit Fett nach hinten gestylt':'19-18',
'Lange Haare mit Fett nach hinten gestylt':'20'}
